language: scala
jdk:
  - oraclejdk8
secure: "<secure_key_here>"
script:
  - sbt clean coverage test && sbt coverageAggregate
after_success: 
  - sbt coveralls
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION
