language: scala
jdk:
    - oraclejdk8
secure: "OGv+ofdFFOuakS+ATmcSdCzSYtxoKOEKCMfF+AUOsK6XFQcKfqbQDv7Xq/UvnxPk0C6VOUeb10xgtcm08ew79pZujUm4DeR+Htds20Q677Z8e5Va2GmgB8+eSFNu39oW2zS2VFlU2Rp1jbiQutlmak6YRbKn9hs53ftZNMV1kksCT8zEK4BtpmvdeIK/fAT80ue4EkVcxUw8LYLaAVOiBFkeU34Hvd9o3cWy9KGybZzZfl/WTOyVDik8Sb8CTncAzIpibMkaXRKmwa6sXm/5ATOvFZhTryEGIqhD6+2Ufxv5DukV92NVtXyB/aXERDbWRsXopC8k8B7Rdq7yvjIQYwqkq72oW24gjaBDWZY3mo/zBtrIDNt6HqNsJRrBwCSktwpgQc3mJRDkoEd1IzmrzqO2EWnouYX0cyRHp4ybsbl+br2w9ewu1FI0uLaqppS70RUFAlv2tnrPWUXVX3kUeSR/dY3rL9bUGoAcFfQwg5cmkg1fSr8nj7VGIlhdtYHLS43g6K7xHI13S7xMyRkdjgP045yGS5tepgWYSbciLd15Ey4lPhde3/jYU5xFMWBMFymP9yUu+DppesE7ecrJsN1ELyQQ32506QLRHt9glZ1BWHqghsmkuLeEY9mGMMIo84JRuJjb2A7ZHr+Cd3JyiSDh5dZ1zY33SBkrWiRwpkA="
script:
- sbt scoverage:test

after_success: 
    - coveralls
